# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: stgA
  jobs:
  - deployment: jobA1 
    pool:
      vmImage: $(vmImageName)
    environment: 'sampleEnvA1'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo A1!
  - deployment: jobA2
    pool:
      vmImage: $(vmImageName)
    environment: 'sampleEnvA2'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo A2!

- stage: stgB
  dependsOn: stgA
  jobs:
  - deployment: jobB1 
    pool:
      vmImage: $(vmImageName)
    environment: 'sampleEnvB1'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo B1!
  - deployment: jobB2
    pool:
      vmImage: $(vmImageName)
    environment: 'sampleEnvB2'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo B2!
